### ISSUE TITLE
Cross Build Instructions: rename needed

### ISSUE THREAD

**Issue by Shamar** [minnyres/amule-win32#2]
Following the (great) [build instructions](https://github.com/minnyres/amule-win32/wiki/How-to:-build-aMule-2.3.3), I had an error due to a mismatch in the library names expected by the aMule build script.

I resolved with a simple rename:
```
~/amule-build/tmp/wxwidgets/lib$ 
ls *.a|xargs -n 1 bash -c 'mv $0 `echo $0 | sed "s/-i686-w64-mingw32//"`'
```

After that building aMule worked fine.

(further note: I disabled maxmind geo-ip, but for personal privacy preferences)

**Comment by minnyres** [comment]
Hi. Thanks for the feedback. Please provide the version of the Linux distribution, GCC, and Mingw-w64 so that I can make a test.

**Comment by Shamar** [comment]
Debian Buster
```
$ i686-w64-mingw32-gcc --version
i686-w64-mingw32-gcc (GCC) 8.3-win32 20190406
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
