### ISSUE TITLE
is aMule broken?

### ISSUE THREAD

**Issue by github-userx** [minnyres/amule-win32#3]
Hi

just wondering if aMule is currently broken or not? All downloads for me stop after downloading 15-30MB. They only continue after manually pausing & resuming them. I got highID + ports open/forwarded.  

The aMule (Linux) project seems to be abandoned with all its unresolved issues and few activity on the GitHub page?

i see your Windows Version is 2.3.3.4 ? Ubuntu is 2.3.3. ?

**Comment by github-userx** [comment]
I guess it’s Linux related and aMule on Windows does work. What a shame, I really liked the idea of getting into ed2k file sharing  :( everyone’s got the same issue (unresolved), see:

https://forum.amule.org/index.php?topic=73928.0

http://forum.amule.org/index.php?topic=71860.0
http://forum.amule.org/index.php?topic=70093.0
http://forum.amule.org/index.php?topic=73076.0
http://forum.amule.org/index.php?topic=73240.0

**Comment by minnyres** [comment]
The Windows build here uses the same source code with the official project (except some necessary [patches](https://github.com/minnyres/amule-win32/tree/main/patches)). The version number 2.3.3.4 means the 4th build for aMule 2.3.3.

> All downloads for me stop after downloading 15-30MB.

Although I am running aMule on Linux and not bothered with this bug, I think this blog [on-wrong-header-error-during-downloading-of-amule-v2-3-2-and-later](https://www.emule-secret.com/posts/2021/05/07/on-wrong-header-error-during-downloading-of-amule-v2-3-2-and-later) may be related (the page is Chinese and google translation can help).

> I guess it’s Linux related and aMule on Windows does work.

If this bug only occurs on Linux, I guess it may be caused by the third party dependencies but not the source code of aMule. You can post the ed2k links here so I can help make some tests.

**Comment by github-userx** [comment]
Message ID: ***@***.***>Hi!

Thanks. Much appreciated. I think aMule on Linux is more „stable“ than I originally thought. Downloads mostly finish over time albeit slowly but that’s probably more due to low amount of sources/seeders/uploaders and their speeds. All in all I can’t complain much anymore. Probably just too used to torrents and their speeds.

Again, thanks a lot for the support/help.

**Comment by Leofib191** [comment]
Hello, have changed the URL (http://mailfud.org/geoip-legacy/GeoIP.dat.gz) for GeoIP in amule config file but cannot see any flag.  Any advice? Thanks

**Comment by minnyres** [comment]
@Leofib191 First make sure that you are using the latest build. After shutdown aMule, check the option `GeoIPEnabled` and `GeoLiteCountryUpdateUrl` in `amule.conf`. Also check whether the file `GeoIP.dat` exists. If everything is OK, amule should show the flags of peers like this:

![image](https://user-images.githubusercontent.com/40790553/223142206-98af77d3-bd56-4032-95e0-b6fe5fe25c58.png)

**Comment by Leofib191** [comment]
Hello thanks for replying.

GeoIPEnabled=1 and 
GeoLiteCountryUpdateUrl=http://mailfud.org/geoip-legacy/GeoIP.dat.gz
I think I'm using the latest version: minnyres/amule-dlp:official-2.3.3 

Not sure about Geoip.dat: where should I check?
Thanks

**Comment by minnyres** [comment]
> I think I'm using the latest version: minnyres/amule-dlp:official-2.3.3

@Leofib191 Are you running amule in docker and managing it with amulegui on Windows? You need to check `amule.conf` and `Geoip.dat` for the Windows client at the location `~\AppData\Roaming\aMule\`. Need to use the latest build here: https://github.com/minnyres/amule-win32/releases/tag/v2.3.3.4

**Comment by Leofib191** [comment]
Hello, Have downloaded the latest GUI and it works, thanks!

Are you planning a version of your aMule docker with OpenVPN?

Thanks again!

**Comment by minnyres** [comment]
> Are you planning a version of your aMule docker with OpenVPN?

I will consider the proposal. Can you explain why you need aMule work with OpenVPN？

**Comment by Leofib191** [comment]
I'm anything but an expert, I saw OpenVPN used in other dockers (not aMule), thus I think it's a sort of standard protocol to be used.
There are no aMule dockers with any VPN embedded as far as I know, and would be much needed for the safety of torrenting

**Comment by minnyres** [comment]
> There are no aMule dockers with any VPN embedded as far as I know, and would be much needed for the safety of torrenting

I will take some investigations on building aMule docker images with VPN but it won't be that soon. If you really care about security, set a stronger password for amulegui and amuleweb. You can also try to setup a private network with zerotier

**Comment by Leofib191** [comment]
By security I mean that your IP, i.e. the IP showed by the aMule app, is hidden.
