### ISSUE TITLE
amule-dlp client banned by xtreme dlp

### ISSUE THREAD

**Issue by AxelRUS** [minnyres/amule-win32#5]
eMule XtremeMod 8.1 with antileech.dll (DLP v43) bans amule-dlp client with next message:
`[Bad Modstring Scheme](ban)- Client 1@0.0.0.0 (ip-removed) 'http://www.aMule.org' (aMule v2.3.3 [aMule-dlp 2.3.3-dlp],None/None/None)`

**Comment by AxelRUS** [comment]
Thank you for link!

But aMule users will be banned from xtreme (and other clients with same dlp module) and their download speeds will be slower. Maybe better change modstring (if it's not difficult)?

**Comment by minnyres** [comment]
> Maybe better change modstring (if it's not difficult)?

aMule should not be a banned client, perhaps it is because of the version `v2.3.3` but not the modstring as `v2.3.3` is not released at the age of DLP v43
